name: Monitor API definition for changes

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - saga
    paths:
      - .github/workflows/monitor-changes.yaml

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile
        run: npx tsc
      - name: Download API definition
        run: curl https://api.flexport.com/docs/v2/flexport > api-docs/v2.yaml
      - name: Update client
        run: |
          node dist/bin/generateTypes.js
          node dist/bin/generateApiOperations.js
          npx prettier --write src/**/*.ts
          npx tsc
        continue-on-error: true
      - name: create new branch
        run: |
          CHECKSUM=`sha1sum api-docs/v2.yaml | awk '{ print $1 }' | tr -d '\n'`
          git checkout -b flexport-api-upstream-changes-$CHECKSUM
        id: create-branch
        continue-on-error: true
      - name: Check out branch
        if: steps.create-branch.outcome == 'failure'
        run: |
          CHECKSUM=`sha1sum api-docs/v2.yaml | awk '{ print $1 }' | tr -d '\n'`
          git checkout flexport-api-upstream-changes-$CHECKSUM
      - name: Add changes to git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git checkout -b flexport-api-upstream-changes
          git add -A
          git commit -m 'feat: update generated code

          BREAKING CHANGE: These changes have not been checked by a human.'
      - name: Run tests
        run: npm test
        continue-on-error: true
      - run:
          echo "machine github.com login authtoken password ${GITHUB_TOKEN}" >
          ~/.netrc
      - name: Create PR
        if: steps.create-branch.outcome == 'success'
        run: |
          gh pr create -B saga -b '' -d -t 'Implement Flexport API upstream changes'
      - name: Append PR
        if: steps.create-branch.outcome == 'failure'
        run: |
          git push
