name: Monitor API definition for changes

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - saga
    paths:
      - .github/workflows/monitor-changes.yaml

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile
        run: npx tsc
      - name: Download API definition
        run: curl https://api.flexport.com/docs/v2/flexport > api-docs/v2.yaml
      - name: Update client
        run: |
          node dist/bin/generateTypes.js
          node dist/bin/generateApiOperations.js
          npx prettier --write src/**/*.ts
        continue-on-error: true
      - name: Add changes to git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git checkout -b flexport-api-changes-`uuidgen`
          git add -A
          git commit -m 'fix: update generated code

          BREAKING CHANGE: Changes might be breaking.'
      - name: Run tests
        run: npm test
        continue-on-error: true
      - name: Install GitHub CLI
        run: |
          curl -L https://github.com/cli/cli/releases/download/v0.10.0/gh_0.10.0_linux_amd64.deb > gh_0.10.0_linux_amd64.deb
          sudo apt install ./gh_*_linux_amd64.deb
      - name: Create PR
        run: gh pr create --fill -d
