name: Monitor API definition for changes

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - saga
    paths:
      - .github/workflows/monitor-changes.yaml

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile
        run: npx tsc
      - name: Download API definition
        run: |
          curl https://api.flexport.com/docs/v2/flexport > api-docs/v2.yaml
          git add -A
      - name: Update client
        run: |
          node dist/bin/generateTypes.js
          node dist/bin/generateApiOperations.js
      - name: Run tests
        run: npm test
        continue-on-error: true
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "saga"
          pr_title: "fix: update client to the latest definition"
